export default function Head() {
  return (
    <>
      <title>Codelex 20.task</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.png" />
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/foundation-sites@6.7.5/dist/css/foundation.min.css" crossOrigin="anonymous" precedence="default" />
    </>
  )
}
